/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CodemonGUI */

#ifndef _Included_CodemonGUI
#define _Included_CodemonGUI
#ifdef __cplusplus
extern "C" {
#endif
#undef CodemonGUI_H_GAP
#define CodemonGUI_H_GAP 10L
#undef CodemonGUI_V_GAP
#define CodemonGUI_V_GAP 4L
#undef CodemonGUI_BORDER_WIDTH
#define CodemonGUI_BORDER_WIDTH 5L
#undef CodemonGUI_REPORTS_WIDTH
#define CodemonGUI_REPORTS_WIDTH 200L
#undef CodemonGUI_MAXTURNS
#define CodemonGUI_MAXTURNS 10000L
/*
 * Class:     CodemonGUI
 * Method:    sendTest
 * Signature: (Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_CodemonGUI_sendTest
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     CodemonGUI
 * Method:    sendTestBattle
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_CodemonGUI_sendTestBattle
  (JNIEnv *, jobject, jstring, jstring, jint);

/*
 * Class:     CodemonGUI
 * Method:    sendBattle
 * Signature: (Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_CodemonGUI_sendBattle
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     CodemonGUI
 * Method:    parseTextFile
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_CodemonGUI_parseTextFile
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     CodemonGUI
 * Method:    getReport
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_CodemonGUI_getReport
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
